# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklikebox',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_facebook_facebooklikebox', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='facebooklikebutton',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_facebook_facebooklikebutton', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
